id: P010327
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:15.290045
source_metadata:
  id: bdr:W3CN1338
  title: བཀའ་མ་ཐེག་པ་རིམ་དགུའི་ཕྲིན་ཆོག་མཐའ་དག་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པའི་དཀར་ཆག
  author: ''
  volumes:
    c11a367881d94f038582edcf82e604e1:
      image_group_id: I3CN1340
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
