id: P010327
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1338
  title: བཀའ་མ་ཐེག་པ་རིམ་དགུའི་ཕྲིན་ཆོག་མཐའ་དག་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པའི་དཀར་ཆག
  author: ''
  volumes:
    c11a367881d94f038582edcf82e604e1:
      image_group_id: I3CN1340
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
