id: I578B87EB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:27:34+00:00'
last_modified: '2022-06-08T12:46:33.256841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN1338
  title: བཀའ་མ་ཐེག་པ་རིམ་དགུའི་ཕྲིན་ཆོག་མཐའ་དག་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པའི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DB04:
      image_group_id: I3CN1340
      title: ''
      total_pages: 146
      order: 1
      base_file: DB04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
